// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolicitudServidores.DBContext;

#nullable disable

namespace SolicitudServidores.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("SolicitudServidores.Back.Models.ServerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disk")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<string>("Os")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ram")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ServerRequestId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerRequestId1");

                    b.ToTable("ServidoresEntrada");
                });

            modelBuilder.Entity("SolicitudServidores.Back.Models.ServerRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Architecture")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredServices")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SolicitudServidores");
                });

            modelBuilder.Entity("SolicitudServidores.Models.EvidenciasPruebas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<long>("Id_Servidor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Id_usuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ruta_pdf")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ruta_pdf");

                    b.Property<long?>("id_servidor")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("id_usuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("id_servidor");

                    b.HasIndex("id_usuario");

                    b.ToTable("evidencias_pruebas", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.PermisoCategoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("categoria");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("PermisoCategoria");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Servidor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Almacenamiento")
                        .HasMaxLength(300)
                        .HasColumnType("INTEGER")
                        .HasColumnName("almacenamiento");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("Expiracion")
                        .HasColumnType("date")
                        .HasColumnName("expiracion");

                    b.Property<string>("Funcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("funcion");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("hostname");

                    b.Property<long>("Id_Solicitud")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("LlaveOS")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("llaveOS");

                    b.Property<int>("Nucleos")
                        .HasMaxLength(300)
                        .HasColumnType("INTEGER")
                        .HasColumnName("nucleos");

                    b.Property<int>("Ram")
                        .HasMaxLength(300)
                        .HasColumnType("INTEGER")
                        .HasColumnName("ram");

                    b.Property<string>("SistemaOperativo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("sistemaOperativo");

                    b.Property<long?>("id_solicitud")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("id_solicitud");

                    b.ToTable("servidor", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Solicitud", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Arquitectura")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Arquitectura");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("Fecha_creacion")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<long?>("Id_Usuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Servicios")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("Servicios");

                    b.Property<long?>("id_usuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("id_usuario");

                    b.ToTable("solicitud", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Subdominio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("Fecha_Expiracion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime?>("Fecha_asignacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_asignacion");

                    b.Property<long?>("Id_Servidor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Id_usuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre_url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_url");

                    b.Property<long?>("id_servidor")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("id_usuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("id_servidor");

                    b.HasIndex("id_usuario");

                    b.ToTable("subdominio", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("correo");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text")
                        .HasColumnName("imagen");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("contrasena");

                    b.Property<string>("Permisos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permisos");

                    b.HasKey("Id");

                    b.ToTable("usuarios", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.VPN", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("Fecha_Expiracion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime?>("Fecha_asignacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_asignacion");

                    b.Property<long>("Id_servidor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Id_usuario_Responsable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<long?>("id_servidor")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("id_usuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("id_servidor");

                    b.HasIndex("id_usuario");

                    b.ToTable("vpn", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Models.WAF", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<long>("Id_Servidor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Id_usuario")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("id_servidor")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("id_usuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("id_servidor");

                    b.HasIndex("id_usuario");

                    b.ToTable("waf", "public");
                });

            modelBuilder.Entity("SolicitudServidores.Back.Models.ServerEntry", b =>
                {
                    b.HasOne("SolicitudServidores.Back.Models.ServerRequest", null)
                        .WithMany("Servers")
                        .HasForeignKey("ServerRequestId1");
                });

            modelBuilder.Entity("SolicitudServidores.Models.EvidenciasPruebas", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Servidor", "Servidor")
                        .WithMany()
                        .HasForeignKey("id_servidor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SolicitudServidores.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Servidor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolicitudServidores.Models.PermisoCategoria", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Usuario", "Usuario")
                        .WithMany("PermisoCategorias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Servidor", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("id_solicitud")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Solicitud", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Subdominio", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Servidor", "Servidor")
                        .WithMany()
                        .HasForeignKey("id_servidor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SolicitudServidores.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Servidor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolicitudServidores.Models.VPN", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Servidor", "Servidor")
                        .WithMany()
                        .HasForeignKey("id_servidor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SolicitudServidores.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Servidor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolicitudServidores.Models.WAF", b =>
                {
                    b.HasOne("SolicitudServidores.Models.Servidor", "Servidor")
                        .WithMany()
                        .HasForeignKey("id_servidor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SolicitudServidores.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Servidor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolicitudServidores.Back.Models.ServerRequest", b =>
                {
                    b.Navigation("Servers");
                });

            modelBuilder.Entity("SolicitudServidores.Models.Usuario", b =>
                {
                    b.Navigation("PermisoCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
